### ISSUE TITLE
Duplicate colors in palette

### ISSUE THREAD

**Issue by henriquea** [henriquea/that-color#1]
The [terminal-kit](https://www.npmjs.com/package/terminal-kit#ref.colors) `bgColorRgb()` picks the closest match for an RGB value. The problem with this is that the **nearest** colours output is the same. 

<img width="158" alt="screen shot 2016-12-09 at 15 20 10" src="https://cloud.githubusercontent.com/assets/123278/21053970/9846e7ec-be23-11e6-9558-d6957d651f7f.png">

**Comment by Qix-** [comment]
I guess I'm not following - why is this unexpected behavior? There are only so many colors available to a terminal in certain modes.

**Comment by henriquea** [comment]
@qix- not saying this is unexpected. Just trying to find a solution 🤓

**Comment by Qix-** [comment]
There isn't, unless you use the Truecolor escape (`\x1b[38;2;<r>;<g>;<b>m`).

**Comment by henriquea** [comment]
You're legend @Qix- works like a charm now. Thanks!
